### ISSUE TITLE
Improvements to Traceroute MaDDash grid

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/maddash#99]
It has been reported by some users that the traceroute grid displayed by MaDDash is confusing. A green grid doesn't mean that traceroute measurements are conclusive, i.e. that they reach the final destination. A green grid only means that the path seen by traceroute is not changing. And in the case of a trace being blocked at the first hop, it is not going to change unless the packets are not blocked anymore. MaDDash is then showing a green grid but the traceroute probes are not reaching their destination (see example below).

This is seen as confusing to some users.  But at the same time not all traceroute targets will accept trace probes reaching them and checking if there is a path change to a target that is blocking trace probes is a valid use case too.

### Proposal
Ivan and I are proposing we have 2 different behaviours for the trace Nagios check and maddash grid.

1. the default check will be the current behaviour, i.e. not if the trace is conclusive or not doesn't matter
2. when giving an option to the check, for example `-e|--endpoint`, the check will also verify that the endpoint is reachable

### Current behaviour example
Here is an example with the trace between ps01 and ps14 where the grid is showing a green square when the trace is stopped at an intermediate router interface.
<img width="349" alt="traceroute-grid" src="https://user-images.githubusercontent.com/484879/105711304-4a900500-5f10-11eb-8350-af4ec5a19d53.png">
<img width="511" alt="traceroute path" src="https://user-images.githubusercontent.com/484879/105711311-4d8af580-5f10-11eb-9881-17a45e0ca027.png">

**Comment by tonin** [comment]
We should also review other traceroute check related requests like https://github.com/perfsonar/nagios/issues/18 and https://github.com/perfsonar/nagios/issues/14

**Comment by igarny** [comment]
In general this request sounds reasonable, BUT there are cases, which remain underspecified and unclear:
1) The plugin counts the changes of paths. Since failure to reach the end point cannot be a count for path changes then it is unclear on how to interpret the failure. The options for a Nagios plugin are:
- report as missing data?
- report as no deviation / no change = generally the current implementation
- report as a random low value, to trigger a WARNING = very tricky / impossible / unfeasible to implement
- report as a huge number of path changes to trigger Critical = somewhat tricky

2)
Also It remains unclear the case where a mixture of collected paths are found with both reaching and missing the end point
Please specify in terms of the above options.

Please keep in mind the Nagios plugin allows only for the above possible states.
